# Generated by Django 4.0.2 on 2022-02-09 22:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='date_published',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
