# Generated by Django 4.0.2 on 2022-02-11 10:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_thumbnail_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
