# Generated by Django 4.0.2 on 2022-02-11 11:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogpost_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
